export const QUERY_KEYS = {
  agents: ["agents"] as const,
  archivedAgents: ["archivedAgents"] as const,
  currentAgent: (userId?: string) => ["currentAgent", userId] as const,
  policies: (filters?: object) => ["policies", filters] as const,
  drafts: ["drafts"] as const,
  commissionPayouts: (filters?: object) => ["commissionPayouts", filters] as const,
  commissionLevels: ["commissionLevels"] as const,
  rateAdjustments: ["rateAdjustments"] as const,
  carriers: ["carriers"] as const,
  carrierOptions: ["carrierOptions"] as const,
  positions: ["positions"] as const,
  agentContracts: (agentId?: string) => ["agentContracts", agentId] as const,
  contracts: ["contracts"] as const,
  payrollRuns: ["payrollRuns"] as const,
  activeAgents: ["activeAgents"] as const,
  webhookConfigs: ["webhookConfigs"] as const,
  tenant: ["tenant"] as const,
  tenantFromDomain: ["tenantFromDomain"] as const,
  carrierProfiles: ["carrierProfiles"] as const,
  carrierAliases: ["carrierAliases"] as const,
  billingSnapshots: ["billingSnapshots"] as const,
  subscription: ["subscription"] as const,
} as const;
